-- Frida Restaurant initial Supabase schema.
-- Run this in Supabase SQL Editor after the project is ready.

create extension if not exists pgcrypto;

create table if not exists public.staff_profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  login_email text,
  username text not null unique check (username ~ '^[a-z0-9._-]+$'),
  role text not null check (role in ('admin', 'kitchen', 'cashier')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.staff_profiles add column if not exists login_email text;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  display_id bigint generated by default as identity,
  order_type text not null check (order_type in ('dine_in', 'takeaway', 'delivery')),
  status text not null check (status in ('pending', 'accepted', 'preparing', 'ready', 'delivered', 'rejected', 'cancelled')),
  customer_name text not null,
  customer_phone text not null,
  customer_email text,
  table_label text,
  delivery_address text,
  notes text,
  subtotal numeric(10, 2) not null default 0,
  tax numeric(10, 2) not null default 0,
  delivery_fee numeric(10, 2) not null default 0,
  total numeric(10, 2) not null default 0,
  payment_method text not null default 'cash',
  payment_status text not null default 'unpaid',
  invoice jsonb,
  source text not null default 'web',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  menu_item_id text,
  name text not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric(10, 2) not null default 0,
  total numeric(10, 2) not null default 0,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.order_status_events (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  status text not null check (status in ('pending', 'accepted', 'preparing', 'ready', 'delivered', 'rejected', 'cancelled')),
  staff_profile_id uuid references public.staff_profiles(id) on delete set null,
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.reservations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  phone text not null,
  email text,
  reservation_date date,
  reservation_time time,
  party_size integer not null default 1 check (party_size > 0),
  occasion text,
  allergies text,
  notes text,
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'cancelled', 'completed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.notification_tokens (
  id uuid primary key default gen_random_uuid(),
  order_id uuid references public.orders(id) on delete cascade,
  customer_phone text,
  token text not null unique,
  platform text not null default 'web',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.app_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_by_staff_profile_id uuid references public.staff_profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.staff_profiles enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.order_status_events enable row level security;
alter table public.reservations enable row level security;
alter table public.notification_tokens enable row level security;
alter table public.app_settings enable row level security;

-- The app backend uses the service role key, which bypasses RLS.
-- Keep direct browser access closed until we intentionally add public policies.

create index if not exists idx_orders_status_created_at on public.orders(status, created_at desc);
create index if not exists idx_orders_type_status on public.orders(order_type, status);
create index if not exists idx_order_items_order_id on public.order_items(order_id);
create index if not exists idx_reservations_created_at on public.reservations(created_at desc);
create index if not exists idx_notification_tokens_order_id on public.notification_tokens(order_id);
create unique index if not exists idx_staff_profiles_login_email_unique
  on public.staff_profiles (lower(login_email))
  where login_email is not null;
